//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CargaHoraria { get; set; }
        public int ProfessorId { get; set; }
    
        public virtual Professor Professor { get; set; }
    }
}
